### ISSUE TITLE
3.6出现错误

### ISSUE THREAD

**Issue by guhchh** [jizhihaoSAMA/OCR-GALGAME-SystemTray#2]
![SharedScreenshot](https://user-images.githubusercontent.com/64550274/80630522-f04c3b80-8a86-11ea-9ad1-8616e55dadcf.jpg)

**Comment by jizhihaoSAMA** [comment]
配置文件需要更新，在新版需要user.json和setting.json 两个json，我更新了releases
![image](https://user-images.githubusercontent.com/48234827/80657933-77190c80-8ab7-11ea-96b8-23dba9c51286.png)

**Comment by guhchh** [comment]
没问题了，感谢

**Comment by guhchh** [comment]
> 配置文件需要更新，在新版需要user.json和setting.json 两个json，我更新了releases
> ![image](https://user-images.githubusercontent.com/48234827/80657933-77190c80-8ab7-11ea-96b8-23dba9c51286.png)
没问题了，感谢
